env: dev11
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Ce5dknB2y%*n
    url: jdbc:mysql://172.16.113.128:3306/springCloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 172.16.113.128
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
girl: 
  name: zhangsan
  age: 66
